import type { ReportDefinition } from './designer-contracts'

const invoiceTemplate: ReportDefinition = {
	version: 1,
	name: 'Invoice (Band Designer)',
	description: 'Invoice with repeating detail rows and totals footer.',
	page: {
		size: 'A4',
		orientation: 'portrait',
		margins: { top: 24, right: 24, bottom: 24, left: 24 },
	},
	bands: [
		{
			id: 'invoice-report-header',
			type: 'reportHeader',
			height: 110,
			canGrow: true,
			elements: [
				{
					id: 'invoice-title',
					kind: 'textbox',
					x: 0,
					y: 4,
					width: 540,
					height: 30,
					staticText: 'INVOICE',
					font: {
						family: 'Helvetica',
						size: 24,
						weight: 'bold',
						style: 'normal',
						color: '#0f172a',
						align: 'left',
						lineHeight: 1.2,
					},
				},
				{
					id: 'invoice-no',
					kind: 'textbox',
					x: 0,
					y: 44,
					width: 260,
					height: 18,
					expression: '=Summary.invoiceNo',
					staticText: 'Invoice Number',
				},
				{
					id: 'invoice-date',
					kind: 'textbox',
					x: 280,
					y: 44,
					width: 260,
					height: 18,
					expression: '=DateFormat(Summary.postingDate, "yyyy-MM-dd")',
				},
			],
		},
		{
			id: 'invoice-page-header',
			type: 'pageHeader',
			height: 30,
			canGrow: false,
			elements: [
				{
					id: 'header-desc',
					kind: 'textbox',
					x: 0,
					y: 8,
					width: 220,
					height: 16,
					staticText: 'Description',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'left',
						lineHeight: 1.2,
					},
				},
				{
					id: 'header-qty',
					kind: 'textbox',
					x: 260,
					y: 8,
					width: 80,
					height: 16,
					staticText: 'Qty',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'header-unit',
					kind: 'textbox',
					x: 350,
					y: 8,
					width: 80,
					height: 16,
					staticText: 'Unit',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'header-amount',
					kind: 'textbox',
					x: 440,
					y: 8,
					width: 100,
					height: 16,
					staticText: 'Amount',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
		{
			id: 'invoice-detail',
			type: 'detail',
			height: 20,
			canGrow: true,
			elements: [
				{
					id: 'detail-desc',
					kind: 'textbox',
					x: 0,
					y: 0,
					width: 220,
					height: 18,
					expression: '=Fields.description',
				},
				{
					id: 'detail-qty',
					kind: 'textbox',
					x: 260,
					y: 0,
					width: 80,
					height: 18,
					expression: '=Fields.quantity',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'detail-unit',
					kind: 'textbox',
					x: 350,
					y: 0,
					width: 80,
					height: 18,
					expression: '=Format(Fields.unitPrice, "currency")',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'detail-amount',
					kind: 'textbox',
					x: 440,
					y: 0,
					width: 100,
					height: 18,
					expression: '=Format(Fields.lineAmount, "currency")',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
		{
			id: 'invoice-report-footer',
			type: 'reportFooter',
			height: 54,
			canGrow: false,
			elements: [
				{
					id: 'total-label',
					kind: 'textbox',
					x: 350,
					y: 6,
					width: 80,
					height: 18,
					staticText: 'TOTAL',
					font: {
						family: 'Helvetica',
						size: 12,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'total-value',
					kind: 'textbox',
					x: 440,
					y: 6,
					width: 100,
					height: 18,
					expression: '=Format(Sum(Fields.lineAmount), "currency")',
					font: {
						family: 'Helvetica',
						size: 12,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
		{
			id: 'invoice-page-footer',
			type: 'pageFooter',
			height: 22,
			canGrow: false,
			elements: [
				{
					id: 'page-no',
					kind: 'textbox',
					x: 380,
					y: 4,
					width: 160,
					height: 14,
					expression: '=Globals.PageNumber + " / " + Globals.TotalPages',
					font: {
						family: 'Helvetica',
						size: 9,
						weight: 'normal',
						style: 'normal',
						color: '#64748b',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
	],
}

const thermalTemplate: ReportDefinition = {
	version: 1,
	name: 'POS Receipt (Thermal)',
	description: '80mm thermal receipt with compact spacing.',
	page: {
		size: 'THERMAL',
		orientation: 'portrait',
		margins: { top: 14, right: 10, bottom: 18, left: 10 },
	},
	bands: [
		{
			id: 'thermal-header',
			type: 'reportHeader',
			height: 62,
			canGrow: true,
			elements: [
				{
					id: 'store-name',
					kind: 'textbox',
					x: 0,
					y: 2,
					width: 206,
					height: 16,
					staticText: 'UPLINK STORE',
					font: {
						family: 'Courier',
						size: 12,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'center',
						lineHeight: 1.1,
					},
				},
				{
					id: 'receipt-no',
					kind: 'textbox',
					x: 0,
					y: 24,
					width: 206,
					height: 14,
					expression: '=Summary.receiptNo',
					font: {
						family: 'Courier',
						size: 9,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'center',
						lineHeight: 1.1,
					},
				},
				{
					id: 'receipt-date',
					kind: 'textbox',
					x: 0,
					y: 40,
					width: 206,
					height: 14,
					expression: '=DateFormat(Summary.generatedAt, "yyyy-MM-dd")',
					font: {
						family: 'Courier',
						size: 9,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'center',
						lineHeight: 1.1,
					},
				},
			],
		},
		{
			id: 'thermal-detail',
			type: 'detail',
			height: 16,
			canGrow: true,
			elements: [
				{
					id: 'line-name',
					kind: 'textbox',
					x: 0,
					y: 0,
					width: 122,
					height: 14,
					expression: '=Fields.description',
					font: {
						family: 'Courier',
						size: 8,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'left',
						lineHeight: 1.1,
					},
				},
				{
					id: 'line-qty',
					kind: 'textbox',
					x: 124,
					y: 0,
					width: 28,
					height: 14,
					expression: '=Fields.quantity',
					font: {
						family: 'Courier',
						size: 8,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.1,
					},
				},
				{
					id: 'line-total',
					kind: 'textbox',
					x: 154,
					y: 0,
					width: 52,
					height: 14,
					expression: '=Format(Fields.lineAmount, "number")',
					font: {
						family: 'Courier',
						size: 8,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.1,
					},
				},
			],
		},
		{
			id: 'thermal-footer',
			type: 'reportFooter',
			height: 38,
			canGrow: false,
			elements: [
				{
					id: 'grand-total-label',
					kind: 'textbox',
					x: 0,
					y: 6,
					width: 112,
					height: 14,
					staticText: 'TOTAL',
					font: {
						family: 'Courier',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'left',
						lineHeight: 1.1,
					},
				},
				{
					id: 'grand-total-value',
					kind: 'textbox',
					x: 114,
					y: 6,
					width: 92,
					height: 14,
					expression: '=Format(Sum(Fields.lineAmount), "number")',
					font: {
						family: 'Courier',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.1,
					},
				},
			],
		},
	],
}

const purchaseOrderTemplate: ReportDefinition = {
	version: 1,
	name: 'Purchase Order',
	page: {
		size: 'A4',
		orientation: 'portrait',
		margins: { top: 24, right: 24, bottom: 24, left: 24 },
	},
	bands: [
		{
			id: 'po-header',
			type: 'reportHeader',
			height: 92,
			canGrow: true,
			elements: [
				{
					id: 'po-title',
					kind: 'textbox',
					x: 0,
					y: 4,
					width: 540,
					height: 28,
					staticText: 'PURCHASE ORDER',
					font: {
						family: 'Helvetica',
						size: 22,
						weight: 'bold',
						style: 'normal',
						color: '#0f172a',
						align: 'left',
						lineHeight: 1.2,
					},
				},
				{
					id: 'po-vendor',
					kind: 'textbox',
					x: 0,
					y: 42,
					width: 540,
					height: 16,
					expression: '=Summary.vendor_name',
				},
			],
		},
		{
			id: 'po-detail',
			type: 'detail',
			height: 22,
			canGrow: true,
			elements: [
				{
					id: 'po-item',
					kind: 'textbox',
					x: 0,
					y: 0,
					width: 280,
					height: 18,
					expression: '=Fields.description',
				},
				{
					id: 'po-qty',
					kind: 'textbox',
					x: 282,
					y: 0,
					width: 80,
					height: 18,
					expression: '=Fields.quantity',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'po-cost',
					kind: 'textbox',
					x: 366,
					y: 0,
					width: 80,
					height: 18,
					expression: '=Format(Fields.unitCost, "currency")',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
				{
					id: 'po-amount',
					kind: 'textbox',
					x: 450,
					y: 0,
					width: 90,
					height: 18,
					expression: '=Format(Fields.lineAmount, "currency")',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
	],
}

const salesSummaryTemplate: ReportDefinition = {
	version: 1,
	name: 'Sales Summary by Category',
	page: {
		size: 'A4',
		orientation: 'portrait',
		margins: { top: 24, right: 24, bottom: 24, left: 24 },
	},
	bands: [
		{
			id: 'summary-header',
			type: 'reportHeader',
			height: 70,
			canGrow: true,
			elements: [
				{
					id: 'summary-title',
					kind: 'textbox',
					x: 0,
					y: 4,
					width: 540,
					height: 24,
					staticText: 'Sales Summary',
					font: {
						family: 'Helvetica',
						size: 20,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'left',
						lineHeight: 1.2,
					},
				},
			],
		},
		{
			id: 'summary-group-header',
			type: 'groupHeader',
			height: 24,
			canGrow: false,
			groupExpression: '=Fields.category',
			elements: [
				{
					id: 'summary-category',
					kind: 'textbox',
					x: 0,
					y: 4,
					width: 540,
					height: 16,
					expression: '=Fields.category',
					background: '#e2e8f0',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'left',
						lineHeight: 1.2,
					},
				},
			],
		},
		{
			id: 'summary-detail',
			type: 'detail',
			height: 20,
			canGrow: true,
			elements: [
				{
					id: 'summary-item',
					kind: 'textbox',
					x: 12,
					y: 0,
					width: 340,
					height: 16,
					expression: '=Fields.item_description',
				},
				{
					id: 'summary-amount',
					kind: 'textbox',
					x: 360,
					y: 0,
					width: 180,
					height: 16,
					expression: '=Format(Fields.lineAmount, "currency")',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'normal',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
		{
			id: 'summary-group-footer',
			type: 'groupFooter',
			height: 22,
			canGrow: false,
			elements: [
				{
					id: 'summary-subtotal',
					kind: 'textbox',
					x: 360,
					y: 2,
					width: 180,
					height: 16,
					expression: '=Format(Sum(Fields.lineAmount), "currency")',
					font: {
						family: 'Helvetica',
						size: 10,
						weight: 'bold',
						style: 'normal',
						color: '#111827',
						align: 'right',
						lineHeight: 1.2,
					},
				},
			],
		},
	],
}

const DESIGNER_TEMPLATES: Record<string, ReportDefinition> = {
	INVOICE: invoiceTemplate,
	POS_RECEIPT_THERMAL: thermalTemplate,
	PURCHASE_ORDER: purchaseOrderTemplate,
	SALES_SUMMARY: salesSummaryTemplate,
}

export function listDesignerTemplates(): Array<{
	key: string
	definition: ReportDefinition
}> {
	return Object.entries(DESIGNER_TEMPLATES).map(([key, definition]) => ({
		key,
		definition,
	}))
}

export function getDesignerTemplate(key: string): ReportDefinition | undefined {
	return DESIGNER_TEMPLATES[key]
}
