import type { BuiltInLayoutKey, ReportLayout } from './contracts'

const BUILT_INS: Record<BuiltInLayoutKey, ReportLayout> = {
	BLANK_EMPTY: {
		key: 'BLANK_EMPTY',
		name: 'Blank / Empty',
		pageSize: 'A4',
		orientation: 'portrait',
		blocks: [{ kind: 'heading', text: 'Report', level: 1 }],
	},
	A4_SUMMARY: {
		key: 'A4_SUMMARY',
		name: 'A4 Summary',
		pageSize: 'A4',
		orientation: 'portrait',
		blocks: [
			{ kind: 'heading', text: 'Summary Report', level: 1 },
			{ kind: 'spacer', size: 'sm' },
			{ kind: 'keyValue', key: 'Module', valuePath: 'moduleId' },
			{ kind: 'keyValue', key: 'Entity', valuePath: 'entityId' },
			{ kind: 'keyValue', key: 'Generated', valuePath: 'generatedAt' },
			{ kind: 'spacer', size: 'md' },
			{
				kind: 'table',
				columns: [
					{ key: '_id', label: 'ID' },
					{ key: 'status', label: 'Status' },
					{ key: '_updatedAt', label: 'Updated' },
				],
				maxRows: 60,
			},
		],
	},
	THERMAL_RECEIPT: {
		key: 'THERMAL_RECEIPT',
		name: 'Thermal Receipt',
		pageSize: 'THERMAL',
		orientation: 'portrait',
		blocks: [
			{ kind: 'heading', text: 'Receipt', level: 2 },
			{ kind: 'keyValue', key: 'Receipt No', valuePath: 'summary.receiptNo' },
			{ kind: 'keyValue', key: 'Session', valuePath: 'summary.sessionNo' },
			{ kind: 'keyValue', key: 'Payment', valuePath: 'summary.paymentMethod' },
			{ kind: 'spacer', size: 'sm' },
			{
				kind: 'table',
				columns: [
					{ key: 'description', label: 'Item' },
					{ key: 'quantity', label: 'Qty' },
					{ key: 'lineAmount', label: 'Total' },
				],
				maxRows: 120,
			},
			{ kind: 'spacer', size: 'sm' },
			{ kind: 'keyValue', key: 'Subtotal', valuePath: 'summary.subtotal' },
			{ kind: 'keyValue', key: 'Tax', valuePath: 'summary.taxAmount' },
			{
				kind: 'keyValue',
				key: 'Discount',
				valuePath: 'summary.discountAmount',
			},
			{ kind: 'keyValue', key: 'Total', valuePath: 'summary.totalAmount' },
		],
	},
	DOC_SALES_ORDER: {
		key: 'DOC_SALES_ORDER',
		name: 'Sales Order',
		pageSize: 'A4',
		orientation: 'portrait',
		blocks: [
			{ kind: 'heading', text: 'Sales Order', level: 1 },
			{ kind: 'spacer', size: 'sm' },
			{ kind: 'keyValue', key: 'Order No.', valuePath: 'summary.documentNo' },
			{ kind: 'keyValue', key: 'Status', valuePath: 'summary.status' },
			{ kind: 'keyValue', key: 'Order Date', valuePath: 'summary.orderDate' },
			{ kind: 'spacer', size: 'sm' },
			{ kind: 'heading', text: 'Customer', level: 2 },
			{
				kind: 'keyValue',
				key: 'Name',
				valuePath: 'summary.customer.name',
			},
			{
				kind: 'keyValue',
				key: 'Email',
				valuePath: 'summary.customer.email',
			},
			{ kind: 'spacer', size: 'md' },
			{ kind: 'heading', text: 'Order Lines', level: 2 },
			{
				kind: 'table',
				columns: [
					{ key: 'lineNo', label: 'Line' },
					{ key: 'item_description', label: 'Description' },
					{ key: 'quantity', label: 'Qty' },
					{ key: 'unitPrice', label: 'Unit Price' },
					{ key: 'lineAmount', label: 'Amount' },
				],
			},
			{ kind: 'spacer', size: 'sm' },
			{
				kind: 'keyValue',
				key: 'Total Amount',
				valuePath: 'summary.totalAmount',
			},
			{ kind: 'spacer', size: 'sm' },
			{
				kind: 'paragraph',
				text: 'Generated by Uplink Reporting',
			},
		],
	},
	DOC_SALES_INVOICE: {
		key: 'DOC_SALES_INVOICE',
		name: 'Sales Invoice',
		pageSize: 'A4',
		orientation: 'portrait',
		blocks: [
			{
				kind: 'row',
				columns: [
					{
						width: 60,
						blocks: [
							{ kind: 'heading', text: 'Uplink Corp.', level: 1 },
							{
								kind: 'paragraph',
								text: '123 Business Ave, Suite 100\nMetro City, ST 10001\ncontact@uplink.io',
							},
						],
					},
					{
						width: 40,
						blocks: [
							{ kind: 'heading', text: 'INVOICE', level: 1 },
							{
								kind: 'keyValueGroup',
								pairs: [
									{
										key: 'Invoice No.',
										valuePath: 'summary.invoiceNo',
									},
									{ key: 'Date', valuePath: 'summary.postingDate' },
									{
										key: 'Customer ID',
										valuePath: 'summary.customerId',
									},
									{ key: 'Due Date', valuePath: 'summary.dueDate' },
								],
							},
						],
					},
				],
			},
			{ kind: 'spacer', size: 'md' },
			{ kind: 'sectionHeader', text: 'BILL TO', color: '#2c5282' },
			{
				kind: 'paragraph',
				text: '{{summary.customer.name}}\n{{summary.customer.address}}\n{{summary.customer.email}}',
			},
			{ kind: 'spacer', size: 'md' },
			{
				kind: 'table',
				columns: [
					{ key: 'item_description', label: 'Description' },
					{ key: 'taxed', label: 'Taxed' },
					{ key: 'quantity', label: 'Qty' },
					{ key: 'unitPrice', label: 'Unit Price' },
					{ key: 'lineAmount', label: 'Amount' },
				],
			},
			{ kind: 'spacer', size: 'sm' },
			{
				kind: 'row',
				columns: [
					{
						width: 50,
						blocks: [
							{
								kind: 'sectionHeader',
								text: 'OTHER COMMENTS',
								color: '#276749',
							},
							{
								kind: 'paragraph',
								text: 'Payment is due within 30 days of invoice date.\nPlease include invoice number on your payment.',
							},
						],
					},
					{
						width: 50,
						blocks: [
							{
								kind: 'keyValueGroup',
								align: 'right',
								pairs: [
									{
										key: 'Subtotal',
										valuePath: 'summary.subtotal',
									},
									{
										key: 'Taxable',
										valuePath: 'summary.taxableAmount',
									},
									{
										key: 'Tax Rate',
										valuePath: 'summary.taxRate',
									},
									{ key: 'Tax', valuePath: 'summary.taxAmount' },
									{
										key: 'Total',
										valuePath: 'summary.totalAmount',
									},
								],
							},
						],
					},
				],
			},
			{ kind: 'divider' },
			{
				kind: 'paragraph',
				text: 'Thank You For Your Business!',
				align: 'center',
				bold: true,
			},
		],
	},
	DOC_POS_RECEIPT: {
		key: 'DOC_POS_RECEIPT',
		name: 'POS Receipt (A4)',
		pageSize: 'A4',
		orientation: 'portrait',
		blocks: [
			{ kind: 'heading', text: 'POS Receipt', level: 1 },
			{ kind: 'spacer', size: 'sm' },
			{
				kind: 'keyValue',
				key: 'Receipt No.',
				valuePath: 'summary.transactionNo',
			},
			{ kind: 'keyValue', key: 'Status', valuePath: 'summary.status' },
			{
				kind: 'keyValue',
				key: 'Payment',
				valuePath: 'summary.paymentMethod',
			},
			{
				kind: 'keyValue',
				key: 'Session',
				valuePath: 'summary.session.sessionNo',
			},
			{ kind: 'spacer', size: 'md' },
			{ kind: 'heading', text: 'Items', level: 2 },
			{
				kind: 'table',
				columns: [
					{ key: 'description', label: 'Item' },
					{ key: 'quantity', label: 'Qty' },
					{ key: 'unitPrice', label: 'Price' },
					{ key: 'lineAmount', label: 'Total' },
				],
			},
			{ kind: 'spacer', size: 'sm' },
			{
				kind: 'keyValue',
				key: 'Subtotal',
				valuePath: 'summary.subtotal',
			},
			{
				kind: 'keyValue',
				key: 'Tax',
				valuePath: 'summary.taxAmount',
			},
			{
				kind: 'keyValue',
				key: 'Discount',
				valuePath: 'summary.discountAmount',
			},
			{
				kind: 'keyValue',
				key: 'Total',
				valuePath: 'summary.totalAmount',
			},
		],
	},
}

export function listBuiltInLayouts(): ReportLayout[] {
	return Object.values(BUILT_INS)
}

export function getBuiltInLayout(key: string): ReportLayout | undefined {
	return BUILT_INS[key as BuiltInLayoutKey]
}
